version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

    volumes:
      - ./antarctic:/antarctic/antarctic:ro
      - ./test:/antarctic/test
      - ./artifacts:/antarctic/artifacts
      - ./source:/source:ro
      #- ./binder/work:/antarctic/notebooks:ro

  lint:
    build:
       context: .
       dockerfile: Dockerfile
       target: lint

    volumes:
      - ./antarctic:/antarctic/antarctic:ro
      - ./.pylintrc:/antarctic/.pylintrc:ro