version: '3.6'
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./antarctic:/antarctic/antarctic:ro
      - ./test:/antarctic/test
      - ./artifacts:/antarctic/artifacts
      - ./source:/source:ro
      - ./binder/work:/notebooks

