version: '3.6'
services:
  antarctic:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

  jupyter:
    build:
      context: .
      dockerfile: binder/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./binder/work:/home/jovyan/work
    depends_on:
      - mongo

  mongo:
    image: mongo:latest