name: binder

on: [push]

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  Serve-binder-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Construct requirements.txt (with dev-dependencies)
      run: |
        pip install pip-tools
        pip-compile --extra dev -o requirements.txt pyproject.toml
        #mv dev-requirements.txt requirements.txt
        cat requirements.txt
        

    # cache for binder
    - name: cache binder build on mybinder.org
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}
