comp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Install Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      # Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.3
        with:
          virtualenvs-create: false