name: Lint Dockerfile

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

      - name: Lint Jupyter Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "binder/Dockerfile"
