name: Release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Publish Python Package
      uses: mariamrf/py-package-publish-action@v1.1.0
      with:
        python_version: '3.10.0'
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
