# .github/workflows/release.yml
name: Release

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]

jobs:
  build:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # this is more a build
      - uses: cvxgrp/.github/actions/release@main
        with:
          python-version: '3.12'  # Optional, defaults to 3.12
          build-tool: 'hatch'     # Optional, defaults to hatch

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: release

    permissions:
      # This permission is required for trusted publishing.
      id-token: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      # download dist from build
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
