name: Sync Config Templates

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday at 5:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Run config sync script
        run: |
          curl -sSL https://raw.githubusercontent.com/tschm/.config-templates/main/scripts/up.sh | bash

      - name: Create Pull Request if needed
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: sync config files from .config-templates"
          branch: sync/update-configs
          title: "chore: sync config files from .config-templates"
          body: "This PR updates config files from [tschm/.config-templates](https://github.com/tschm/.config-templates)."
          delete-branch: true
